In [ ]:
import numpy as np

In [ ]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[ 8  4  1  7  3]
 [ 9  6  1  2  9]
 [ 6  8  7 10  3]
 [ 3  9  3  2  4]
 [ 1  4  7  1  6]]


In [ ]:
random_float_matrix = np.random.rand(4, 4)
print(random_float_matrix)

[[0.57155205 0.38035107 0.83199846 0.48526305]
 [0.56369323 0.46144826 0.70244092 0.29561138]
 [0.47355925 0.59406055 0.69793669 0.05071849]
 [0.32079381 0.5991105  0.39856221 0.47893931]]


In [ ]:
v1 = np.random.randint(1, 11, size=5)
v2 = np.random.randint(1, 11, size=5)
print(v1)
print(v2)
sum_result = v1 + v2
subtract_result = v1 - v2
multiply_result = v1 * v2
print(sum_result)
print(subtract_result)
print(multiply_result)

[ 1 10  3  1  9]
[ 4  2  7  1 10]
[ 5 12 10  2 19]
[-3  8 -4  0 -1]
[ 4 20 21  1 90]


In [ ]:
v1 = np.random.random(7)
v2 = np.random.random(7)
print(v1)
print(v2)
scalar = np.dot(v1, v2)
print(scalar)

[0.07104361 0.42650214 0.98811057 0.90473611 0.2117829  0.15027431
 0.89059758]
[0.43269323 0.77374587 0.29515527 0.11601553 0.35241691 0.37711273
 0.83745821]
1.6344983220693652


In [ ]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 3))
print(m1)
print(m2)
multiply_result = np.dot(m1, m2)
print(multiply_result)

[[9 2]
 [6 9]]
[[ 7  6 10]
 [ 4  8  7]]
[[ 71  70 104]
 [ 78 108 123]]


In [ ]:
m = np.random.randint(1, 11, size=(3, 3))
print(m)
inverse_m = np.linalg.inv(m)
print(inverse_m)

[[5 8 8]
 [5 5 4]
 [4 7 3]]
[[-0.20634921  0.50793651 -0.12698413]
 [ 0.01587302 -0.26984127  0.31746032]
 [ 0.23809524 -0.04761905 -0.23809524]]


In [ ]:
m = np.random.rand(4, 4)
print(m)
trans_m = m.T
print(trans_m)

[[0.57377824 0.80536316 0.86748753 0.88217924]
 [0.78311346 0.26136545 0.07852193 0.62653386]
 [0.90993443 0.3669391  0.94921796 0.54869023]
 [0.49010649 0.08606549 0.54234539 0.9574856 ]]
[[0.57377824 0.78311346 0.90993443 0.49010649]
 [0.80536316 0.26136545 0.3669391  0.08606549]
 [0.86748753 0.07852193 0.94921796 0.54234539]
 [0.88217924 0.62653386 0.54869023 0.9574856 ]]


In [ ]:
m = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=4)
print(m)
print(v)
multiply_result = np.dot(m, v)
print(multiply_result)

[[ 9  1  9  5]
 [ 2 10  9  6]
 [ 8  9  9  6]]
[ 1  2 10  9]
[146 166 170]


In [ ]:
m = np.random.rand(2, 3)
v = np.random.rand(3)
print(m)
print(v)
multiply_result = np.dot(m, v)
print(multiply_result)

[[0.5267125  0.82634514 0.63370226]
 [0.17656488 0.06978741 0.36334438]]
[0.61726517 0.82548559 0.61011866]
[1.39389086 0.38827904]


In [ ]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print(m1)
print(m2)
result = m1 * m2
result2 = np.multiply(m1, m2)
print(result)
print(result2)

[[6 4]
 [4 2]]
[[3 3]
 [2 3]]
[[18 12]
 [ 8  6]]
[[18 12]
 [ 8  6]]


In [ ]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print(m1)
print(m2)
result = np.dot(m1, m2)
print(result)

[[2 1]
 [8 6]]
[[ 5 10]
 [ 1  6]]
[[ 11  26]
 [ 46 116]]


In [ ]:
m = np.random.randint(1, 101, size=(5, 5))
print(m)
sum_of_elements = np.sum(m)
print(sum_of_elements)

[[95 71 76 23 28]
 [24 30 23 99 55]
 [79 73 73 33 79]
 [53 28 48  8  9]
 [ 8 64 50 11 50]]
1190


In [ ]:
m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
print(m1)
print(m2)
difference_matrix = m1 - m2
print(difference_matrix)

[[ 9  8  8  9]
 [ 3  1  1  9]
 [ 4 10  7 10]
 [ 6  3 10  2]]
[[ 3  9  9  9]
 [ 4  9  5  6]
 [10 10  8  8]
 [ 5  6  5  3]]
[[ 6 -1 -1  0]
 [-1 -8 -4  3]
 [-6  0 -1  2]
 [ 1 -3  5 -1]]


In [ ]:
m = np.random.rand(3, 3)
print(m)
sums_vector = np.sum(m, axis=1, keepdims=True)
print(sums_vector)

[[0.72055124 0.92924049 0.98320189]
 [0.79118471 0.04657908 0.35217602]
 [0.81947681 0.00167824 0.82926296]]
[[2.63299362]
 [1.1899398 ]
 [1.650418  ]]


In [ ]:
m = np.random.randint(-10, 11, size=(3, 4))
print(m)
squares_matrix = np.square(m)
print(squares_matrix)

[[ -4   4   3 -10]
 [ -2   2   8  -5]
 [  4   2   5 -10]]
[[ 16  16   9 100]
 [  4   4  64  25]
 [ 16   4  25 100]]


In [ ]:
v = np.random.randint(1, 51, size=4)
print(v)
sqrt_vector = np.sqrt(v)
print(sqrt_vector)

[29 38 14 43]
[5.38516481 6.164414   3.74165739 6.55743852]
